#服务器名字
spring:
  application:
    name: eureka-server

#服务器端口
server:
  port: 2001

eureka:
  server:
    #自我保护机制
    #eureka 集群服务器之间，通过 hostname 来区分
    #
    #eureka.server.enable-self-preservation
    #
    #eureka 的自我保护状态：心跳失败的比例，在15分钟内是否超过85%,如果出现了超过的情况，Eureka Server会将当前的实例注册信息保护起来，同时提示一个警告，一旦进入保护模式，Eureka Server将会尝试保护其服务注册表中的信息，不再删除服务注册表中的数据。也就是不会注销任何微服务

    enable-self-preservation: false
    #主机名，方便在服务器集群中分辨
  instance:
    hostname: eureka1
  client:
    #单台服务器禁用向自己注册、拉取注册信息
    register-with-eureka: false
    fetch-registry: false


