spring:
  application:
    name: zuul


server:
  port: 3001

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka



zuul:
  routes:
    item-service: /item-service/**
    user-service: /user-service/**
    order-service: /order-service/**
  retryable: true
#Hystrix超时，如果不开启ribbon重试，默认为1s
#hystrix:
#  command:
#    default:
#      isolation:
#        thread:
#          timeoutInMilliseconds: 500

#暴露全部日志
management:
  endpoints:
    web:
      exposure:
        include: "*"

